name: Continuous Integration
  
on:
  pull_request:
    branches:
      - master
  
jobs:
  automation-test-job:
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install and test
        run: |
          npm install
          npm run ci:test

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.9qY7fjZqyyGaYdFA3HuHntfn }}
          vercel-org-id: ${{ secrets.team_1BRDwDEtc3kFWxKhUFSDCrLs }}
          vercel-project-id: ${{ secrets.prj_g2piKv5ls9Z594Pzzn9DQQYhxpMO }}
          vercel-args: '--prod'
